dist: trusty
sudo: require

language: cpp
compiler: g++

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-6.0
      - george-edison55-precise-backports
    packages:
      - clang-6.0
      - cmake-data
      - cmake
env:
  - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - cmake CMAkeLists.txt
  - cmake --built . --target neat