language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7


before_script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - cmake -H. -BBuild
  - cd Build

script:
  - make
  - ctest -V
